import { t as resolvePageComponent } from "./assets/laravel-vite-plugin-D9XPBWcO.js";
import { createInertiaApp } from "@inertiajs/react";
import createServer from "@inertiajs/react/server";
import ReactDOMServer from "react-dom/server";
import { jsx } from "react/jsx-runtime";
//#region resources/js/ssr.jsx
var appName = "coachingsinsikar";
createServer((page) => createInertiaApp({
	page,
	render: ReactDOMServer.renderToString,
	title: (title) => title ? `${title} | ${appName}` : appName,
	resolve: (name) => resolvePageComponent([`./Pages/${name}.jsx`, `./Pages/${name}.tsx`], /* #__PURE__ */ Object.assign({
		"./Pages/Admin/Authors/AuthorForm.tsx": () => import("./assets/AuthorForm-CVureTt-.js"),
		"./Pages/Admin/Authors/Edit.jsx": () => import("./assets/Edit-2feGxL-8.js"),
		"./Pages/Admin/Authors/Index.jsx": () => import("./assets/Index-CmSPKer-.js"),
		"./Pages/Admin/Authors/New.jsx": () => import("./assets/New-BN2ZHUcJ.js"),
		"./Pages/Admin/Businesses/Index.jsx": () => import("./assets/Index-BPZwbQgR.js"),
		"./Pages/Admin/Categories/Index.jsx": () => import("./assets/Index-BHsS1nfw.js"),
		"./Pages/Admin/DeleteButton.jsx": () => import("./assets/DeleteButton-4pbNZztV.js"),
		"./Pages/Admin/Index.jsx": () => import("./assets/Index-DRhuPFSY.js"),
		"./Pages/Admin/Media/Index.jsx": () => import("./assets/Index-D3Irxw5-.js"),
		"./Pages/Admin/PostForm.tsx": () => import("./assets/PostForm-DrDKBz1O.js"),
		"./Pages/Admin/Posts/Edit.jsx": () => import("./assets/Edit-CLKcArvL.js"),
		"./Pages/Admin/Posts/New.jsx": () => import("./assets/New-C6U0BOdg.js"),
		"./Pages/Admin/SeoAudit/Index.jsx": () => import("./assets/Index-CzhOTYPS.js"),
		"./Pages/Admin/Settings/Slider.jsx": () => import("./assets/Slider-CsMGqqLx.js"),
		"./Pages/Admin/Stories/Edit.jsx": () => import("./assets/Edit-Doc-TgKi.js"),
		"./Pages/Admin/Stories/Index.jsx": () => import("./assets/Index-BDLhEfXx.js"),
		"./Pages/Admin/Stories/New.jsx": () => import("./assets/New-DPd2cmP3.js"),
		"./Pages/Admin/Stories/StoryForm.tsx": () => import("./assets/StoryForm-DAJL6eDR.js"),
		"./Pages/Admin/components/MediaPicker.tsx": () => import("./assets/MediaPicker-DhMqFL25.js").then((n) => n.n),
		"./Pages/Auth/ConfirmPassword.jsx": () => import("./assets/ConfirmPassword-D9f_HCJL.js"),
		"./Pages/Auth/ForgotPassword.jsx": () => import("./assets/ForgotPassword-CBmTYLL0.js"),
		"./Pages/Auth/Login.jsx": () => import("./assets/Login-DPiY-XyF.js"),
		"./Pages/Auth/Register.jsx": () => import("./assets/Register-Bi7sdYtY.js"),
		"./Pages/Auth/ResetPassword.jsx": () => import("./assets/ResetPassword-CbUZ3g26.js"),
		"./Pages/Auth/VerifyEmail.jsx": () => import("./assets/VerifyEmail-BZ8zw0zU.js"),
		"./Pages/Author/Index.jsx": () => import("./assets/Index-CRjwF8w_.js"),
		"./Pages/Author/Show.jsx": () => import("./assets/Show-cqs91Tt6.js"),
		"./Pages/Blog/Index.jsx": () => import("./assets/Index-KYskaxAD2.js"),
		"./Pages/Blog/Show.jsx": () => import("./assets/Show-DVVhxFdB.js"),
		"./Pages/Category/Index.jsx": () => import("./assets/Index-BLjI1Lq1.js"),
		"./Pages/Category/Show.jsx": () => import("./assets/Show-BWPLuXB9.js"),
		"./Pages/Community/Create.jsx": () => import("./assets/Create-JstdPD1B.js"),
		"./Pages/Community/Edit.jsx": () => import("./assets/Edit-DJc4wBV32.js"),
		"./Pages/Community/Feed.jsx": () => import("./assets/Feed-Cg2XKcAo.js"),
		"./Pages/Community/ModQueue.jsx": () => import("./assets/ModQueue-D2p4rdJn.js"),
		"./Pages/Community/Show.jsx": () => import("./assets/Show-DGnSi3we.js"),
		"./Pages/Dashboard.jsx": () => import("./assets/Dashboard-Dm9k1hBD.js"),
		"./Pages/Post/Create.jsx": () => import("./assets/Create-2n09CvZ4.js"),
		"./Pages/Post/Show.jsx": () => import("./assets/Show-Czfw51xN.js"),
		"./Pages/Profile/Edit.jsx": () => import("./assets/Edit-Bc839C9Z.js"),
		"./Pages/Profile/Partials/DeleteUserForm.jsx": () => import("./assets/DeleteUserForm-bgs-02f5.js"),
		"./Pages/Profile/Partials/UpdatePasswordForm.jsx": () => import("./assets/UpdatePasswordForm-ClTBBcO-.js"),
		"./Pages/Profile/Partials/UpdateProfileInformationForm.jsx": () => import("./assets/UpdateProfileInformationForm-Dy8I--ud.js"),
		"./Pages/Reviews/Index.tsx": () => import("./assets/Index-Dh_XCza0.js"),
		"./Pages/Reviews/components/AdminPanel.tsx": () => import("./assets/AdminPanel-CFYriZy2.js"),
		"./Pages/Reviews/components/AiSearchModal.tsx": () => import("./assets/AiSearchModal-CfFlaLO8.js"),
		"./Pages/Reviews/components/ApiDocsModal.tsx": () => import("./assets/ApiDocsModal-Cnw480tN.js"),
		"./Pages/Reviews/components/BusinessCard.tsx": () => import("./assets/BusinessCard-Cx1Euq7P.js"),
		"./Pages/Reviews/components/BusinessDashboard.tsx": () => import("./assets/BusinessDashboard-C1JazekU.js"),
		"./Pages/Reviews/components/BusinessProfileView.tsx": () => import("./assets/BusinessProfileView-CTAslfzK.js"),
		"./Pages/Reviews/components/CategoryGrid.tsx": () => import("./assets/CategoryGrid-CMSR5viJ.js"),
		"./Pages/Reviews/components/CreateBusinessModal.tsx": () => import("./assets/CreateBusinessModal-DcLw8nnK.js"),
		"./Pages/Reviews/components/Footer.tsx": () => import("./assets/Footer-D7_QkJak.js"),
		"./Pages/Reviews/components/HeroSection.tsx": () => import("./assets/HeroSection-CXoFLCeq.js"),
		"./Pages/Reviews/components/ModeratorPanel.tsx": () => import("./assets/ModeratorPanel-ChuM8IO4.js"),
		"./Pages/Reviews/components/Navbar.tsx": () => import("./assets/Navbar-BEWFQpzX.js"),
		"./Pages/Reviews/components/SubmitReviewModal.tsx": () => import("./assets/SubmitReviewModal-cV6ol9sx.js"),
		"./Pages/Search/Index.jsx": () => import("./assets/Index-DSiNnndf.js"),
		"./Pages/Static/About.jsx": () => import("./assets/About-Bm_Uj4SN.js"),
		"./Pages/Static/Contact.jsx": () => import("./assets/Contact-CDojTohn.js"),
		"./Pages/Static/EditorialPolicy.jsx": () => import("./assets/EditorialPolicy-pHusUI8R.js"),
		"./Pages/Static/FactCheckingPolicy.jsx": () => import("./assets/FactCheckingPolicy-Dj6AVJYo.js"),
		"./Pages/Static/Privacy.jsx": () => import("./assets/Privacy-CRPDzJX2.js"),
		"./Pages/Static/Terms.jsx": () => import("./assets/Terms-yzeJyU0k.js"),
		"./Pages/Story/Index.jsx": () => import("./assets/Index-CiegvLBT.js"),
		"./Pages/User/Show.jsx": () => import("./assets/Show-BzcbCKvT.js"),
		"./Pages/Welcome.jsx": () => import("./assets/Welcome-CSr6nrMc.js")
	})),
	setup({ App, props }) {
		return /* @__PURE__ */ jsx(App, { ...props });
	}
}));
//#endregion
export {};
